SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
SCREEN_TITLE = 'Hero Man v0.0.1'

CHARACTER_SCALING = 1
TILE_SCALING = 8
SPRITE_PIXEL_SIZE = 16
GRID_PIXEL_SIZE = (SPRITE_PIXEL_SIZE * TILE_SCALING)

PLAYER_MOVEMENT_SPEED = 5

LEFT_VIEWPORT_MARGIN = 32
RIGHT_VIEWPORT_MARGIN = 32
BOTTOM_VIEWPORT_MARGIN = 32
TOP_VIEWPORT_MARGIN = 32