SCREEN_WIDTH = 1420
SCREEN_HEIGHT = 900
SCREEN_TITLE = 'Hero Man v0.0.1'
#1080
#1920
CHARACTER_SCALING = 3
TILE_SCALING = 8
SPRITE_PIXEL_SIZE = 16
GRID_PIXEL_SIZE = (SPRITE_PIXEL_SIZE * TILE_SCALING)

PLAYER_MOVEMENT_SPEED = 5
ENEMY_MOVEMENT_SPEED = 5

LEFT_VIEWPORT_MARGIN = 256
RIGHT_VIEWPORT_MARGIN = 256
BOTTOM_VIEWPORT_MARGIN = 256
TOP_VIEWPORT_MARGIN = 256

LAYERS = ['background', 'path', 'collision', 'player', 'enemy', 'item', 'foreground']